#!/usr/bin/python

import sys,os

files = sys.argv[1:]

trgname = files[0][:files[0].rfind(".")] + ".pdf"

cmd = "convert -quality 15 -verbose %s -pointsize 300 %s" % (" ".join(files), trgname)
print cmd

if os.system(cmd):
    print "Failed"
